### PR TITLE
Made Required Changes in About-Me

### PR DESCRIPTION
**Pull request by sahilsingh2402**
Thank You.

### CODE REVIEW

**Comment by jinwoov** [comment]
Hey Sahil not sure why its giving duplicate file that we merged from before. Could you maybe try to `git pull` before pushing it?

**Comment by sahilsingh2402** [comment]
Then I should have a total of 3 pull requests. But its only 2. Can you
please look into it?

Thabk You😖

**Comment by jinwoov** [comment]
Not sure why its reflecting 2 push. I closed your last pr, because it was going to cause 3 duplicate files so may be thats why?

**Comment by sahilsingh2402** [comment]
Thank You for your response.

**Comment by jinwoov** [comment]
No worries thanks for participating. If it makes it easy for you, you can make pr for two scripts of any content. Knowing your CS skill should be pretty easy 👍 😊

**Comment by sahilsingh2402** [comment]
Can I add more python codes in your repository. Can I do the same challenge
again to create the pull request, or is it not allowed.

Thank You

**Comment by jinwoov** [comment]
That is fine! be creative!

**Pull request closed without merging**
